.TH XmGetSizedPixmap 3 2025-08-04 "Motif 2.4.0"
.SH NAME
XmGetSizedPixmap - Generate a scaled \fBPixmap\fR for an image

.SH SYNOPSIS
.nf
#include <Xm/Xm.h>
.P
\fBXtEnum XmGetSizedPixmap\fR(\fBWidget\fR widget, \fBString\fR image_name,
\fB                       \fR \fBPixel\fR foreground, \fBPixel\fR background,
\fB                       \fR \fBint\fR depth, \fBint\fR width, \fBint\fR height);
.fi

.SH DESCRIPTION
\fBXmGetSizedPixmap\fP loads the image specified by \fIimage_name\fP and
generates a \fBPixmap\fP appropriate for the given \fIdepth\fP, scaled
to the given \fIwidth\fP and \fIheight\fP.

.IP "\fIwidget\fP" 12
Widget used to determine the \fBScreen\fP for which to create the
\fBPixmap\fP.
.IP "\fIimage_name\fP" 12
See \fBXmGetPixmapByDepth\fP for description.
.IP "\fIforeground\fP" 12
See \fBXmGetPixmapByDepth\fP for description.
.IP "\fIbackground\fP" 12
See \fBXmGetPixmapByDepth\fP for description.
.IP "\fIdepth\fP" 12
See \fBXmGetPixmapByDepth\fP for description.
.IP "\fIwidth\fP" 12
Desired \fBPixmap\fP width.
.IP "\fIheight\fP" 12
Desired \fBPixmap\fP height.

.SH RETURN VALUE
A \fBPixmap\fP on success, \fBNULL\fP on error.

.SH ERRORS / WARNINGS
See \fBXmGetPixmapByDepth\fP(3).

.SH SEE ALSO
\fBXmGetPixmapByDepth\fP(3)

.SH AUTHOR
Tim Hentenaar <tim@hentenaar.com>

\"vi:set ft=groff:
