.TH XmGetSizedPixmap 3 "July 2025" "Motif 2.4.0"
.SH SYNOPSIS
.PP
.nf
#include <Xm/Xm.h>
.P
\fBXtEnum XmGetSizedPixmap\fR(\fBWidget\fR widget, \fBString\fR image_name,
\fB                       \fR \fBPixel\fR foreground, \fBPixel\fR background,
\fB                       \fR \fBint\fR depth, \fBint\fR width, \fBint\fR height);
.fi

.SH DESCRIPTION
.PP
\fBXmGetSizedPixmap\fR loads the image specified by \fIimage_name\fR and
generates a \fBPixmap\fR appropriate for the given \fIdepth\fR, scaled
to the given \fIwidth\fR and \fIheight\fR.

.IP "\fIwidget\fP" 12
Widget used to determine the \fBScreen\fR for which to create the
\fBPixmap\fR\&.
.IP "\fIimage_name\fP" 12
See \fBXmGetPixmapByDepth\fP for description.
.IP "\fIforeground\fP" 12
See \fBXmGetPixmapByDepth\fP for description.
.IP "\fIbackground\fP" 12
See \fBXmGetPixmapByDepth\fP for description.
.IP "\fIdepth\fP" 12
See \fBXmGetPixmapByDepth\fP for description.
.IP "\fIwidth\fP" 12
Desired \fBPixmap\fR width.
.IP "\fIheight\fP" 12
Desired \fBPixmap\fR height.

.SH RETURN VALUE
.PP
A \fBPixmap\fR on success, \fBNULL\fR on error.

.SH ERRORS / WARNINGS
.PP
See \fBXmGetPixmapByDepth\fR(3).

.SH SEE ALSO
.PP
\fBXmGetPixmapByDepth\fR(3)

.SH AUTHOR
Tim Hentenaar <tim@hentenaar.com>

\"vi:set ft=groff:
