.TH XmGetSizedPixmap 3 2025-08-04 "Motif 2.4.0"
.SH NAME
XmGetSizedPixmap - Generate a scaled \fBPixmap\fR for an image

.SH SYNOPSIS
.nf
#include <Xm/Xm.h>
.P
\fBPixmap XmGetSizedPixmap\fR(\fBWidget\fR widget, \fBString\fR image_name,
\fB                       \fR \fBPixel\fR foreground, \fBPixel\fR background,
\fB                       \fR \fBint\fR depth, \fBint\fR width, \fBint\fR height);
.fi

.SH DESCRIPTION
\fBXmGetSizedPixmap\fP loads the image specified by \fIimage_name\fP and
generates a \fBPixmap\fP appropriate for the given \fIdepth\fP, scaled
to the given \fIwidth\fP and \fIheight\fP. If an image with similar
properties is found in the image cache, that image will be returned.
Otherwise, the standard paths will be searched for a similarly named
image by way of \fBXmGetIconFilename\fP(3).

.IP "\fIwidget\fP" 12
Widget used to determine the \fBScreen\fP for which to create the
\fBPixmap\fP.
.IP "\fIimage_name\fP" 12
Name of the image from which to generate the pixmap.
.IP "\fIforeground\fP" 12
Foreground color to combine with the image (if the image is a color image).
.IP "\fIbackground\fP" 12
Background color to combine with the image (if the image is a color image).
.IP "\fIdepth\fP" 12
Desired depth for the pixmap.
.IP "\fIwidth\fP" 12
Desired \fBPixmap\fP width.
.IP "\fIheight\fP" 12
Desired \fBPixmap\fP height.

.SH RETURN VALUE
A \fBPixmap\fP on success, \fBNULL\fP on error.

.SH ERRORS / WARNINGS
See \fBXmGetPixmapByDepth\fP(3).

.SH SEE ALSO
\fBXmGetPixmapByDepth\fP(3), \fBXmGetIconFilename\fP(3)

.SH AUTHOR
Tim Hentenaar <tim@hentenaar.com>

\"vi:set ft=groff:
