.TH XMRENDITIONRETRIEVE 3 2026-09-08 "Motif 2.0"
.SH NAME
XmRenditionRetrieve - Retrieve rendition resources

.SH SYNOPSIS
.nf
#include <Xm/Xm.h>

\fBvoid XmRenditionRetrieve\fR(\fBXmRendition \fRrendition,
\fB                        \fR \fBArgList \fRarglist,
\fB                        \fR \fBCardinal \fRargcount);
.fi

.SH DESCRIPTION
This function is obsolete and exists only for compatibility with previous
releases. It has been superceded by \fBXmRenditionGetValues\fP(3). The
current implentation is merely a wrapper around the new function. The
following is an augmented version of the original description.
.PP
\fBXmRenditionRetrieve\fP fetches resource values from a rendition, based
on the names in \fIarglist\fP, in roughly the same manner as \fBXtGetValues\fP.
If the rendition's \fBXmNloadModel\fP is \fBXmLOAD_DEFERRED\fP, the
underlying font is \fBNULL\fP, and the \fBXmNfontName\fP property is not
\fBNULL\fP, the font will be loaded directly so that the \fBXmNfont\fP
value can be properly returned.

.IP "\fIrendition\fP" 10
Specifies the rendition.
.IP "\fIarglist\fP" 10
Specifies the argument list.
.IP "\fIargcount\fP" 10
Specifies the number of attribute/value pairs in the argument list.

.SH CAVEAT DRACONEM
For resources stored as pointers, the original implementation did \fBnot\fP
copy the underlying value. The present implementation returns copies of
any underlying \fBString\fP values or the tab list. This applies
primarily to \fBXmNtag\fP and \fBXmNfontName\fP, as the other \fBString\fP
properties that are now present did not exist when the original
implementation was in use. The current implementation does return a
copy for \fBXmNtabList\fP. Thus, applications using this function, that
made their own copies of the returned values will end up leaking the
copies generated by the new implementation.

\fBXmNfont\fP and \fBXmNxftFont\fP are \fInot\fP copied, thus care must
be taken to ensure they don't get rug-pulled out from under the rendition.

.SH HISTORY
This was added in Motif 2.0, and deprecated in Motif 2.6.0.

.SH SEE ALSO
\fBXmRendition\fP(3), \fBXmRenditionGetValues\fP(3),
\fBXmRenditionSetValues\fP(3), \fBXtGetValues\fP(3)

.SH AUTHOR
Tim Hentenaar <tim@hentenaar.com>

\"vi:set ft=groff:
