.TH XMRENDITION 3 2026-09-08 "Motif 2.6.0"
.SH NAME
XmRendition - Motif Font Abstraction

.SH SYNOPSIS
.nf
#include <Xm/Xm.h>
.fi

.SH DESCRIPTION
\fBXmRendition\fP is a pseudo-widget used as an abstraction over the
various font types available on the system. This data structure is
intentionally opaque, and contains information about a particular
font, and certain stylistic parameters, which are exposed though the
resources given below. \fBXmRendition\fP's resources can be accessed
through the \fBXmRenditionGetValues\fP and \fBXmRenditionSetValues\fP
functions, patterned after \fBXtGetValues\fP and \fBXtSetValues\fP. As
it is not a true \fBWidget\fP, calling the Xt functions on it will
certainly fail.

Renditions inform the compound string (\fBXmString\fP) drawing code about
how a particular string, or part of a string, should be drawn. This
association is based on matching the rendition's tag against that of the
compound string within a \fBXmRenderTable\fP. Though stylistic
parameters such as color and line type are available on the rendition,
primarily for establishing defaults, full advantage should be taken of
the \fBXmRenditionStyle\fP type to convey programmatically-defined
instances of those properties for drawing rather than modifying those
properties of the rendition.

.SH FONT LOADING
For \fBXmRendition\fP to load a font, it must have a load model, type,
and pattern. The pattern (\fIXmNfontName\fP) is the textual string used
to load the font. This will be a XLFD string for X fonts and fontsets,
or a Fontconfig pattern string for Xft fonts.

Modifying font specification resources (\fIXmNfontName\fP,
\fIXmNfontType\fP, \fIXmNfont\fP, \fIXmNxftFont\fP, \fIXmNloadModel\fP)
of a rendition will cause the underlying font to be unloaded and reloaded,
save for externally loaded fonts (see below). Setting \fIXmNfont\fP or
\fIXmNxftFont\fP will force the loading model to \fBXmUNSPECIFIED_LOAD_MODEL\fP.

A rendition can be checked to see if the font was loaded successfully
with \fBXmRenditionIsLoaded\fP. Loading failures will generally emit a
warning message to standard output.

.SS IMMEDIATE LOADING
By specifying the load model as \fBXmLOAD_IMMEDIATE\fP, the font will be
loaded when the \fBXmRendition\fP object is created.

.SS DEFERRED LOADING
A rendition may have the load model \fBXmLOAD_DEFERRED\fP, indicating that
the underlying font will be materialized the first time the rendition is
used to render a compound string or a part thereof; or the first time its
resource properties are queried.

.SS ON-DEMAND LOADING
The \fBXmLOAD_LAZY\fP model indicates that the user will explicitly
manage the loading of the font using the \fBXmRenditionLoad\fP and
\fBXmRenditionUnload\fP functions.

.SS EXTERNAL LOADING
\fBXmUNSPECIFIED_LOAD_MODEL\fP is used for cases where the user wants
to handle the font loading themselves. This is acheived by specifying
the \fIXmNfontType\fP and the corresponding \fIXmNfont\fP or \fIXmNxftFont\fP
property. Motif will not take ownership of such fonts, and will expect
the user to manage their lifecycle. Care must be taken to ensure that
the font type agrees with the provided font object.

.SH EXAMPLES
.SS LOADING A FONT
The simplest way to load a font is by passing a perpared set of arguments
to \fBXmRenditionCreate\fP. For example, to load the X font "fixed":
.PP
.EX
Arg arg[3];
XmRendition r;

XtSetArg(arg[0], XmNloadModel, XmLOAD_IMMEDIATE);
XtSetArg(arg[1], XmNfontType, XmFONT_IS_FONT);
XtSetArg(arg[2], XmNfontName, "fixed");
r = XmRenditionCreate(NULL, XmSTRING_DEFAULT_CHARSET, arg, 3);
if (r && XmRenditionIsLoaded(r)) {
	/* ... */
	XmRenditionFree(r);
}
.EE

.SH LOADING A XFT FONT
For Xft fonts, the metadata properties may be specified in the arguments
given to \fBXmRenditionCreate\fP. These are added to the Fontconfig pattern
that will be matched to load the font. When the font is loaded, the
font-supplied values will replace them. A 12-point sans-serif font could
thus be loaded:
.PP
.EX
XtSetArg(arg[0], XmNloadModel, XmLOAD_IMMEDIATE);
XtSetArg(arg[1], XmNfontType, XmFONT_IS_XFT);
XtSetArg(arg[2], XmNfontName, "sans-serif");
XtSetArg(arg[3], XmNfontSize, 12);
r = XmRenditionCreate(NULL, XmSTRING_DEFAULT_CHARSET, arg, 4);
.EE

.SH RESOURCES
.TS
tab(|) box;
cb s s s s
lb| lb| lb| lb| lb
l| lb| lb| l| l.
XmRendition Resource Set
=
Name|Class|Type|Default|Access
_
XmNloadModel|XmCLoadModel|unsigned char|XmUNSPECIFIED_LOAD_MODEL|CSG
XmNfontType|XmCFontType|XmFontType|XmAS_IS|CSG
XmNtag|XmCTag|XmStringTag|XmS|CG
XmNfont|XmCFont|XtPointer|NULL|CSG
XmNxftFont|XmCXftFont|XtPointer|NULL|CSG
XmNfontName|XmCFontName|String|NULL|CSG
XmNfontFoundry|XmCFontFoundry|String|NULL|CG
XmNfontFamily|XmCFontFamily|String|NULL|CG
XmNfontStyle|XmCFontStyle|String|NULL|CG
XmNfontSize|XmCFontSize|int|0|CG
XmNfontPixelSize|XmCFontPixelSize|int|0|CG
XmNfontSlant|XmCFontSlant|int|XmAS_IS|CG
XmNfontWeight|XmCFontWeight|int|XmAS_IS|CG
XmNwidth|XmCWidth|int|0|G
XmNinkWidth|XmCInkWidth|int|0|G
XmNascent|XmCAscent|int|0|G
XmNdescent|XmCDescent|int|0|G
XmNtabList|XmCTabList|XmTabList|NULL|CSG
XmNrenditionBackground|XmCRenditionBackground|Pixel|XmUNSPECIFIED_PIXEL|CSG
XmNrenditionForeground|XmCRenditionForeground|Pixel|XmUNSPECIFIED_PIXEL|CSG
XmNunderlineType|XmCUnderlineType|unsigned char|XmAS_IS|CSG
XmNstrikethruType|XmCStrikethruType|unsigned char|XmAS_IS|CSG
XmNforegroundState|XmCGroundState|unsigned char|XmAS_IS|CSG
XmNbackgroundState|XmCGroundState|unsigned char|XmAS_IS|CSG
.TE

.IP "\fBXmNloadModel\fP" 8
As previously discussed, this specifies the loading model to use. Valid
values are:
.RS 8
.IP \(bu 4
\fBXmUNSPECIFIED_LOAD_MODEL\fP \(em The font is user-supplied.
.IP \(bu 4
\fBXmLOAD_DEFERRED\fP \(em Load the font on first use.
.IP \(bu 4
\fBXmLOAD_IMMEDIATE\fP \(em Load the font at XmRendition creation.
.IP \(bu 4
\fBXmLOAD_LAZY\fP \(em Load the font on-demand with \fBXmRenditionLoad\fP.
.RE

.IP "\fBXmNfontType\fP" 8
This indicates the type of font being used and must be one of:
.RS 8
.IP \(bu 4
\fBXmFONT_IS_FONT\fP \(em Plain X font
.IP \(bu 4
\fBXmFONT_IS_FONTSET\fP \(em X fontset
.IP \(bu 4
\fBXmFONT_IS_XFT\fP \(em Xft font
.RE

.IP "\fBXmNtag\fP" 8
.RS 8
Tag (\fBXmStringTag\fP) to use for selecting this rendition for rendering.
This value may be queried, but is fixed once the rendition is created.
.RE

.IP "\fBXmNfont\fP" 8
.RS 8
Depending on font type, \fBXFontStruct *\fP or \fBXFontSet\fP associated
with this rendition, cast to \fBXtPointer\fP.
.RE

.IP "\fBXmNxftFont\fP" 8
.RS 8
\fBXftFont *\fP associated with this rendition, cast to \fBXtPointer\fP.
.RE

.IP "\fBXmNfontName\fP" 8
.RS 8
Specification string for this rendition. For X fonts this will be a
X Logical Font Description (XLFD) string, and for Xft fonts, a
Fontconfig pattern string.
.RE

.IP "\fBXmNfontFoundry\fP" 8
.RS 8
Font foundry string, supplied by the font.
.RE

.IP "\fBXmNfontFamily\fP" 8
.RS 8
Font family string, supplied by the font.
.RE

.IP "\fBXmNfontStyle\fP" 8
.RS 8
Font style string, only supplied by Xft fonts.
.RE

.IP "\fBXmNfontSize\fP" 8
.RS 8
Font size in points, supplied by the font.
.RE

.IP "\fBXmNfontPixelSize\fP" 8
.RS 8
Font size in pixels. For Xft fonts, this is supplied by the font, for X
fonts, this is calculated based on the screen DPI and point size,
.RE

.IP "\fBXmNfontSlant\fP" 8
.RS 8
Slant value supplied by the font. Motif pre-defines the following
constants for convenience:
.IP \(bu 4
\fBXmSLANT_ROMAN\fP \(em Regular, upright slant.
.IP \(bu 4
\fBXmSLANT_ITALIC\fP \(em Right-slanted glyphs which may be narrower than
their roman counterparts, usually inspired by handwriting.
.IP \(bu 4
\fBXmSLANT_OBLIQUE\fP \(em Simply right-slanted versions of roman glyphs.
.RE

.IP "\fBXmNfontWeight\fP" 8
.RS 8
Weight value supplied by the font. Motif pre-defines the following
constants for convenience:
.IP \(bu 4
\fBXmWEIGHT_REGULAR\fP \(em Regular weight.
.IP \(bu 4
\fBXmWEIGHT_MEDIUM\fP \(em Medium weight between regular and bold, ideal
for emphasis.
.IP \(bu 4
\fBXmWEIGHT_DEMIBOLD\fP \(em Darker than medium, lighter than bold.
.IP \(bu 4
\fBXmWEIGHT_BOLD\fP \(em Heavy weight ideal for strong text or headers.
.RE

.IP "\fBXmNwidth\fP" 8
.RS 8
Indicated maximum layout width for a glyph in the font in pixels.
.RE

.IP "\fBXmNinkWidth\fP" 8
.RS 8
Indicated maximum ink width for a glyph in the font in pixels.
.RE

.IP "\fBXmNascent\fP" 8
.RS 8
Indicated ascent value for the font in pixels.
.RE

.IP "\fBXmNdescent\fP" 8
.RS 8
Indicated descent value for the font in pixels.
.RE

.IP "\fBXmNtabList\fP" 8
.RS 8
Specifies the tab list which specifies how compound strings containing
tab components are laid out in columns.
.RE

.IP "\fBXmNrenditionForeground\fP" 8
.IP "\fBXmNrenditionBackground\fP" 8
.RS 8
Specifies the foreground or background color for the rendition, as a
\fBPixel\fP value. A value of \fBXmUNSPECIFIED_PIXEL\fP indiciates that
that particular color is not set for this rendition.

The resource converter for this field (applied when these are loaded via
X resources) expects an X color name, or the special string
"unspecified_pixel".
.RE

.IP "\fBXmNforegroundState\fP" 8
.IP "\fBXmNbackgroundState\fP" 8
.RS 8
If ether of these resources are set to \fBXmFORCE_COLOR\fP, the respective
color specified in the rendition will be preferred over values from other
styles/renditions evaluated when rendering a compound string (or part
thereof). These resources have been present at least as far back as
Motif 2.1.30 and were heretofore undocumented.
.RE

.IP "\fBXmNunderlineType\fP" 8
.IP "\fBXmNstrikethruType\fP" 8
.RS 8
Specifies the line type for striking through or underlining a compound
string. Valid values are:
.IP \(bu 4
\fBXmAS_IS\fP \(em The value is unspecified.
.IP \(bu 4
\fBXmNO_LINE\fP \(em Strikethrough / underline will not be applied.
.IP \(bu 4
\fBXmSINGLE_LINE\fP \(em A single line will be used.
.IP \(bu 4
\fBXmDOUBLE_LINE\fP \(em A double line will be used.
.IP \(bu 4
\fBXmSINGLE_DASHED_LINE\fP \(em A single-dashed line will be used.
.IP \(bu 4
\fBXmDOUBLE_DASHED_LINE\fP \(em A double-dashed line will be used.
.RE

.SH HISTORY
\fBXmRendition\fP was added to Motif sometime around version 2.0 as a
replacement for the prior \fBXmFont\fP abstraction, and was updated
to include support for Xft fonts in Motif 2.3.0. The font metrics and
metadata properties (e.g., \fIXmNascent\fP, \fIXmNfontFamily\fP), along
with \fBXmRenditionStyle\fP were added in version 2.6.0.

.SH SEE ALSO
\fBXmRenditionStyle\fP(3), \fBXmRenderTable\fP(3), \fBXmString\fP(3)

.SH AUTHOR
Tim Hentenaar <tim@hentenaar.com>

\"vi:set ft=groff:
