.TH XMRENDERTABLE 3 2026-09-13 "Motif 2.6.0"
.SH NAME
XmRenderTable - Table of renditions for rendering

.SH SYNOPSIS
.nf
#include <Xm/Xm.h>
.fi

.SH DESCRIPTION
\fBXmRenderTable\fP is a grouping of \fBXmRendition\fP instances into
a singular unit which directs how strings (or parts thereof) should
be rendered. Renditions in the table are indexed by tag, and used at
run-time to resolve which font, and default style properties are to be
used in rendering. Render tables can be constructed at run-time, or
specified via X resources, and applied to Motif widgets via the
\fBXmNrenderTable\fP resource.

If the render table is not specified via \fBXmNrenderTable\fP, Motif
widgets can employ the \fBXmeGetDefaultRenderTable\fP function to obtain
a suitable render table from any of their parents that hold the
\fBXmQTspecifyRenderTable\fP trait. As \fBVendorShell\fP holds this trait,
it should always be possible to obtain a render table in this manner.

For application-defined styling of text, the \fBXmRenditionStyle\fP and
\fBXmStringDrawStyled\fP set of routines should be leveraged for text
rendering. See the \fBXmRenderTableResolve\fP(3) page for a description
of how renditions are resolved for rendering.

.SH X RESOURCES
Render tables can be specified in X resource files with lines like the
following:
.EX
\fIresource_spec\fP: [ \fItag\fP [, \fItag\fP ]* ]
.EE

Renditions are then added to the table by tag, and thier resources are
specified thus:
.EX
\fIresource_spec\fP [*|.] \fItag\fP [*|.] \fIresource\fP: \fIvalue\fP
.EE

The older \fBXmFontList\fP resource syntax for X fonts and fontsets is
deprecated, though it remains for backward compatibility and is given
below for reference.

For a font:
.EX
\fIresource_spec\fP: \fIfont_name\fP
\fIresource_spec\fP: \fIfont_name\fP=\fItag\fP
.EE

For a fontset:
.EX
\fIresource_spec\fP: \fIfont_name\fP:\fItag\fP
.EE

.IP "\fIresource_spec\fP" 8
Specifies the render table.
.IP "\fItag\fP" 8
Is a string suitable for the \fBXmNtag\fP resource of \fBXmRendition\fP.
.IP "\fIresource\fP" 8
Is the name of a \fBXmRendition\fP resource.
.IP "\fIvalue\fP" 8
Is a value suitable for the given resource.
.IP "\fIfont_name\fP" 8
A value suitable for \fBXmRendition\fP's \fBXmNfontName\fP resource.

.SH REPRESENTATION CONVERSION

For some rendition resources, type converters have been added for
additional convenience in specifying values via X resource files.
These will typically be stringified versions of the corresponding
constant, without the "Xm" prefix and will be case insensitive. The
\fBfontSlant\fP and \fBfontWeight\fP resources are only considered for
Xft fonts (alternatively, \fBfontStyle\fP can be specified).

.SS fontSlant

Motif defines three slant constants, \fBXmSLANT_ROMAN\fP,
\fBXmSLANT_ITALIC\fP, and \fBXmSLANT_OBLIQUE\fP, which can be specified
as follows:
.EX
*fontSlant: roman
*fontSlant: italic
*fontSlant: oblique
.EE

.SS fontType

For the three font types, \fBXmFONT_IS_FONT\fP, \fBXmFONT_IS_FONTSET\fP,
and \fBXmFONT_IS_XFT\fP, the same applies:
.EX
*fontType: font
*fontType: fontset
*fontType: xft
.EE

.PP
The older names are retained for backward compatibility:
.EX
*fontType: font_is_font
*fontType: font_is_fontset
*fontType: font_is_xft
.EE

.SS fontWeight

For weight, Motif defines four constants: \fBXmWEIGHT_REGULAR\fP,
\fBXmWEIGHT_MEDIUM\fP, \fBXmWEIGHT_DEMIBOLD\fP, and \fBXmWEIGHT_BOLD\fP,
but the representation type includes all of the weight values supplied
by Fontconfig, and may be any of the following:

.EX
thin, extralight, ultralight, light, demilight, semilight, book, regular,
normal, medium, demibold, semibold, bold, extrabold, ultrabold, black,
heavy, extrablack, ultrablack
.EE

.SH EXAMPLES
.SS DEFAULT RENDITION
This example sets the default rendition to the Xft font "sans-serif" with
a size of 8 points. The first line is needed to invoke the conversion that
causes the render table to be created. This is equivalent to adding a
similar rendition to the table with the tag \fBXmFONTLIST_DEFAULT_TAG\fP.

.EX
*renderTable:
*renderTable.fontName: sans-serif
*renderTable.fontType: xft
*renderTable.fontSize: 8
.EE

.SS X FONT
This loads a font for the \fIISO8859-1\fP character set.

.EX
*renderTable: ISO8859-1
*renderTable.ISO8859-1.fontName: *-*-*-medium-r-*-*-*-100-*-*-*-*-iso8859-1
*renderTable.ISO8859-1.fontType: font
.EE

.SS X FONTSET
This loads a fontset which will be used with compound strings that have
the \fBbold\fP tag.

.EX
*renderTable: bold
*renderTable.bold.fontName: *-*-*-bold-r-*-*-*-180-*-*-*-*-*-*
*renderTable.bold.fontType: fontset
.EE

.SH USAGE IN UIL
To specify a render table in \fBUIL\fP(5), you must create a render table
object with the renditions to be added to the table's \fIcontrols\fP. This
example creates a render table with a singular rendition which will have
a tag of "rend", and load a monospace Xft font with a size of 8 points.

.EX
object label_table : XmRenderTable {
	controls {
		XmRendition rend;
	};
};

object rend : XmRendition {
	arguments {
		XmNfontName  = "monospace";
		XmNfontType  = XmFONT_IS_XFT;
		XmNfontSize  = 8;
		XmNloadModel = XmLOAD_IMMEDIATE;
	};
};
.EE

This can be added to a widget by specifying the table as its
\fBXmNrenderTable\fP argument.

.EX
object label : XmLabel {
	arguments {
		XmNrenderTable = label_table;
		XmNlabelString = compound_string('Hello, world!');
	};
	controls {
		XmRenderTable label_table;
	};
};
.EE

Some widgets (e.g., \fBXmBulletinBoard\fP) are a special case, and care
must be taken to ensure that the render table is the first control in
the \fIcontrols\fP list so that it gets created before the other children,
otherwise they will pull the default render table instead of the
intended render table.

.EX
object bb : XmBulletinBoard {
	arguments {
		XmNbuttonRenderTable = button_table;
	};
	controls {
		XmRenderTable button_table;
		XmPushButton  button;
	};
};
.EE

.SH CAVEAT DRACONES
Prior to Motif 2.0, the \fBXmNfontList\fP resource was used to specify the
set of renditions a particular widget was to use. This resource is deprecated,
and \fBXmNrenderTable\fP should be used instead. \fBXmNrenderTable\fP
generally uses the same resource offset as the prior \fBXmNfontList\fP,
the two datatypes being synonymous, thus specifying both resources leads
to undefined behavior.

.SH HISTORY
\fBXmRenderTable\fP was added to Motif 2.0 as a replacement for the prior
\fBXmFontList\fP. Motif 2.6.0 optimized the functionality of the render
table, with improved tag indexing and a new rendition resolution routine
whereby applications can request the precise rendition to be used for
rendering text with a given tag. Motif 2.6.0 also added shorter variants
of the stringified fontType representations.

.SH SEE ALSO
\fBXmRendition\fP(3), \fBXmRenditionStyle\fP(3), \fBXmStringDrawStyled\fP(3),
\fBVendorShell\fP(3), \fBXmRenderTableResolve\fP(3)

.SH AUTHOR
Tim Hentenaar <tim@hentenaar.com>

\"vi:set ft=groff:
