.TH XMRENDITIONUPDATE 3 2026-09-08 "Motif 2.0"
.SH NAME
XmRenditionUpdate - Modify rendition resources

.SH SYNOPSIS
.nf
#include <Xm/Xm.h>

\fBvoid XmRenditionUpdate\fR(\fBXmRendition \fRrendition,
\fB                      \fR \fBArgList \fRarglist,
\fB                      \fR \fBCardinal \fRargcount);
.fi

.SH DESCRIPTION
This function is obsolete and exists only for compatibility with previous
releases. It has been superceded by \fBXmRenditionSetValues\fP(3). The
current implentation is merely a wrapper around the new function. The
following is an augmented version of the original description.
.PP
\fBXmRenditionRetrieve\fP modifies resource values on a rendition, based
on the names in \fIarglist\fP, in roughly the same manner as \fBXtSetValues\fP.
If the \fBXmNfontName\fP property is modified, the underlying font will
be reloaded.

.IP "\fIrendition\fP" 10
Specifies the rendition.
.IP "\fIarglist\fP" 10
Specifies the argument list.
.IP "\fIargcount\fP" 10
Specifies the number of attribute/value pairs in the argument list.

.SH HISTORY
This was added in Motif 2.0, and deprecated in Motif 2.6.0.

.SH SEE ALSO
\fBXmRendition\fP(3), \fBXmRenditionGetValues\fP(3),
\fBXmRenditionSetValues\fP(3), \fBXtSetValues\fP(3)

.SH AUTHOR
Tim Hentenaar <tim@hentenaar.com>

\"vi:set ft=groff:
