.TH XMRENDERTABLEADDRENDITIONS 3 2026-09-16 "Motif 2.0"
.SH NAME
XmRenderTableAddRenditions - Add renditions to a render table

.SH SYNOPSIS
.nf
#include <Xm/Xm.h>

\fBXmRenderTable XmRenderTableAddRenditions\fR(\fBXmRenderTable\fR oldtable,
\fB                                        \fR \fBXmRendition *\fRrenditions,
\fB                                        \fR \fBCardinal\fR rendition_count,
\fB                                        \fR \fBXmMergeMode\fR merge_mode);
.fi

.SH DESCRIPTION
Add a series of renditions to a render table, handling tag conflicts
according to \fImerge_mode\fP. After the additions are complete, the
original table is freed.

.IP "\fItable\fP" 12
Render table to add to (or \fBNULL\fP).
.IP "\fIrenditions\fP" 12
List of renditions to add.
.IP "\fIrendition_count\fP" 12
Number of renditions in the list.
.IP "\fImerge_mode\fP" 12
Manner in which to resolve tag conflicts.

.SH MERGE MODES
The following values are valid for \fImerge_mode\fP.

.RS 8
.IP \(bu 2
\fBXmMERGE_OLD\fP \(em Takes the rendition in the table, replacing any
default values with the values from the rendition in the list.
.IP \(bu 2
\fBXmMERGE_NEW\fP \(em Takes the rendition in the list, replacing any
default values with the values from the rendition in the table.
.IP \(bu 2
\fBXmMERGE_REPLACE\fP \(em Takes the rendition in the list, ignoring the
one in the table.
.IP \(bu 2
\fBXmDUPLICATE\fP \(em Takes both renditions.
.IP \(bu 2
\fBXmSKIP\fP \(em Takes neither rendition.
.RE

.SH RETURN VALUE
A newly-allocated render table containing the result of merging the given
table with the rendition list. The resulting table must be freed with
\fBXmRenderTableFree\fP(3). If the rendition list is \fBNULL\fP, or
the count is zero, the orginal table is returned intact.

.SH HISTORY
This was added in Motif 2.0, but \fBXmDUPLICATE\fP was not previously
documented, despite being used in the code since at least Motif 2.3.1.

.SH SEE ALSO
\fBXmRenderTableRemoveRenditions\fP(3), \fBXmRenderTableFree\fP(3)

.SH AUTHOR
Tim Hentenaar <tim@hentenaar.com>

\"vi:set ft=groff:
