.TH XMRENDERTABLEGETTAGS 3 2026-09-16 "Motif 2.0"
.SH NAME
XmRenderTableGetTags - Get a list of all tags in a render table

.SH SYNOPSIS
.nf
#include <Xm/Xm.h>

\fBint XmRenderTableGetTags\fR(\fBXmRenderTable\fR table,
\fB                        \fR \fBXmStringTag **\fRtag_list);
.fi

.SH DESCRIPTION
Scan the render table, yielding a list of all tags present in the table.

.IP "\fItable\fP" 12
Render table to search.
.IP "\fItag_list\fP" 12
Output parameter which receives the tag list.

.SH RETURN VALUE
Returns the number of entries stored in \fI*tag_list\fP. Zero will be
returned if \fItag_list\fP is NULL, or if the render table is empty.
The tags in the returned list, as well as the list itself, must be freed
with \fBXtFree\fP(3).

.SH SEE ALSO
\fBXmRenderTableGetRenditions\fP(3)

.SH AUTHOR
Tim Hentenaar <tim@hentenaar.com>

\"vi:set ft=groff:
