.TH XMRENDITIONSTYLEFREE 3 2026-09-08 "Motif 2.6.0"
.SH NAME
XmRenditionStyleFree - Free a rendition style

.SH SYNOPSIS
.nf
#include <Xm/Xm.h>
.P
\fBvoid XmRenditionStyleFree\fR(\fBXmRenditionStyle\fR style);
.fi

.SH DESCRIPTION
Free the given rendition style.

.IP "\fIstyle\fP" 12
Rendition style to free.

.SH SEE ALSO
\fBXmRenditionStyle\fP(3), \fBXmRenditionStyleCreate\fP(3),
\fBXmRenditionStyleDup\fP(3)

.SH AUTHOR
Tim Hentenaar <tim@hentenaar.com>

\"vi:set ft=groff:
