.TH XMRENDITIONCREATE 3 2026-09-08 "Motif 2.6.0"
.SH NAME
XmRenditionCreate - Create a rendition

.SH SYNOPSIS
.nf
#include <Xm/Xm.h>

\fBXmRendition XmRenditionCreate\fR(\fBWidget \fRwidget,
\fB                             \fR \fBXmStringTag \fRtag,
\fB                             \fR \fBArgList \fRargs,
\fB                             \fR \fBCardinal \fRcount);
.fi

.SH DESCRIPTION
Create a new rendition with the properties given in \fIargs\fP, using
default values for any property not included in \fIargs\fP. The \fItag\fP
property must be specified and non-NULL. If \fIwidget\fP is \fBNULL\fP,
the default display is used.

If the load model is \fBXmLOAD_IMMEDIATE\fP, the font will be loaded
before this function returns. If the font fails to load, and the
\fBXmNnoFontCallback\fP is set on \fBXmDisplay\fP, the callback will
be called.

.IP "\fIwidget\fP" 12
Widget (or \fBXmRenderTable\fP cast to \fBWidget\fP) from whence to
get the display, or \fBNULL\fP.
.IP "\fItag\fP" 12
Tag to use
.IP "\fIargs\fP" 12
Specifies the argument list.
.IP "\fIcount\fP" 12
Specifies the number of attribute/value pairs in the argument list.

.SH RETURN VALUE
A newly-created \fBXmRendition\fP or \fBNULL\fP on failure. The resulting
rendition must be freed with \fBXmRenditionFree\fP(3).

.SH SEE ALSO
\fBXmRendition\fP(3), \fBXmDisplay\fP(3), \fBXmRenditionFree\fP(3)

.SH AUTHOR
Tim Hentenaar <tim@hentenaar.com>

\"vi:set ft=groff:
