.TH XMRENDITIONFREE 3 2026-09-08 "Motif 2.0"
.SH NAME
XmRenditionFree - Free a rendition

.SH SYNOPSIS
.nf
#include <Xm/Xm.h>

\fBvoid XmRenditionFree\fR(\fBXmRendition \fRrendition);
.fi

.SH DESCRIPTION

Free the storage allocated for a rendition. If the load model is not
\fBXmUNSPECIFIED_LOAD_MODEL\fP, the underlying font is also freed.

.IP "\fIrendition\fP" 10
Rendition to free.

.SH HISTORY
Historically, the underlying font was \fBnot\fP freed by this function.
Motif 2.3.0 added the behavior of freeing the rendition's Xft font when
the rendition itself was freed. Motif 2.6.0 normalized this function's
behavior to free the font when the rendition is freed unless the font is
user-provided.

.SH SEE ALSO
\fBXmRendition\fP(3), \fBXmRenditionCreate\fP(3)

.SH AUTHOR
Tim Hentenaar <tim@hentenaar.com>

\"vi:set ft=groff:
