.TH XMRENDERTABLEFREE 3 2026-09-16 "Motif 2.0"
.SH NAME
XmRenderTableFree - Free a render table

.SH SYNOPSIS
.nf
#include <Xm/Xm.h>

\fBvoid XmRenderTableFree\fR(\fBXmRenderTable\fR table);
.fi

.SH DESCRIPTION
Free any renditions in \fItable\fP and release the allocated heap
memory used for \fItable\fP.

.IP "\fItable\fP" 12
Render table to free.

.SH SEE ALSO
\fBXmRenderTableCreate\fP(3), \fBXmRenditionFree\fP(3)

.SH AUTHOR
Tim Hentenaar <tim@hentenaar.com>

\"vi:set ft=groff:
