.TH XMRENDERTABLEGETRENDITION 3 2026-09-16 "Motif 2.6.0"
.SH NAME
XmRenderTableGetRendition - Retrieve one rendition from a render table

.SH SYNOPSIS
.nf
#include <Xm/Xm.h>

\fBXmRendition XmRenderTableGetRendition\fR(\fBXmRenderTable\fR table,
\fB                                     \fR \fBXmStringTag\fR tag);
.fi

.SH DESCRIPTION
Retrieve the first rendition matching the given tag from a render table,
and return a copy of it. This is effectively the same as calling
\fBXmRenderTableGetRenditions\fP with a singular tag.

Note that the returned copy is a shallow copy of the rendition, not a
duplicate.

.IP "\fItable\fP" 12
Render table to search.
.IP "\fItag\fP" 12
Tag to match against.

.SH RETURN VALUE
A copy of the matching rendition, or \fBNULL\fP if no match was found
in the table. The resulting rendition must be freed with
\fBXmRenditionFree\fP(3).

.SH SEE ALSO
\fBXmRenderTableGetRenditions\fP(3), \fBXmRenditionFree\fP(3)

.SH AUTHOR
Tim Hentenaar <tim@hentenaar.com>

\"vi:set ft=groff:
