.TH XMRENDERTABLECVTTOPROP 3 2026-09-14 "Motif 2.6.0"
.SH NAME
XmRenderTableCvtToProp - Serialize a render table

.SH SYNOPSIS
.nf
#include <Xm/Xm.h>

\fBunsigned int XmRenderTableCvtToProp\fR(\fBWidget\fR widget,
\fB                                   \fR \fBXmRenderTable\fR table,
\fB                                   \fR \fBchar **\fRprop_return);
.fi

.SH DESCRIPTION
This function converts a render table to serialized form, suitable for
transfer over the selection with the \fB_MOTIF_RENDER_TABLE\fP atom.
If \fIprop_return\fP is set, it will receive a pointer to an allocated
memory area containing the serialized representation.

.IP "\fIwidget\fP" 12
Widget from whence to get the display, or \fBNULL\fP.
.IP "\fItable\fP" 12
Render table to serialize.
.IP "\fIprop_return\fP" 12
Return parameter for the serialized representation.

.SH RETURN VALUE
The number of bytes stored (or which would be stored) in \fIprop_return\fP.
The pointer returned in \fIprop_return\fP must be freed with \fBXtFree\fP(3).
On failure, zero is returned on failure, and \fIprop_return\fP, if specified,
is set to \fBNULL\fP.

.SH SEE ALSO
\fBXmRendition\fP(3), \fBXmRenderTableCvtFromProp\fP(3)

.SH HISTORY
This function was introduced in Motif 2.0, and seems to have gone largely
unused. It was neglected, and not updated for Xft support in Motif 2.3.0.
The original implementation serialized the rendertable into a human-readable
string, but in Motif 2.6.0, this has been rewritten to use a TLV-style
binary format.

.SH AUTHOR
Tim Hentenaar <tim@hentenaar.com>

\"vi:set ft=groff:
