.TH XMRENDITIONSTYLEMERGE 3 2026-09-08 "Motif 2.6.0"
.SH NAME
XmRenditionStyleMerge - Merge one rendition style into another

.SH SYNOPSIS
.nf
#include <Xm/Xm.h>
.P
\fBBoolean XmRenditionStyleMerge\fR(\fBXmRenditionStyle\fR a,
\fB                             \fR \fBconst XmRenditionStyle\fR b);
.fi

.SH DESCRIPTION
Replace default values in \fIa\fP with those from \fIb\fP for all style
properties (\fIgc\fP excluded). This facilitates the cascading of styles
across renditions when a compound string (or portion thereof) is
affected by multiple tags.

.IP "\fIa\fP" 12
Target rendition style to merge into.
.IP "\fIb\fP" 12
Source rendition style.

.SH RETURN VALUE
Returns \fBTrue\fP if \fIa\fP was modified, \fBFalse\fP otherwise.

.SH SEE ALSO
\fBXmRenditionStyle\fP(3), \fBXmRenditionStyleCreate\fP(3),
\fBXmRenditionStyleFree\fP(3)

.SH AUTHOR
Tim Hentenaar <tim@hentenaar.com>

\"vi:set ft=groff:
