.TH XMRENDERTABLEGETRENDITIONS 3 2026-09-16 "Motif 2.0"
.SH NAME
XmRenderTableGetRenditions - Retrieve matching renditions from a render table

.SH SYNOPSIS
.nf
#include <Xm/Xm.h>

\fBXmRendition *XmRenderTableGetRenditions\fR(\fBXmRenderTable\fR table,
\fB                                       \fR \fBXmStringTag *\fRtags,
\fB                                       \fR \fBCardinal\fP tag_count);
.fi

.SH DESCRIPTION
For each given tag, return a copy of the first matching rendition in the
table. If a tag cannot be found in the table, the corresponding index in
the resulting list will be NULL.

The tags are evaluated one-by-one, thus, if the same tag is specified
multiple times, the resulting array will contain multiple copies of the
same rendition.

Note that the copies returned are shallow copies of the renditions, not
duplicates.

.IP "\fItable\fP" 12
Render table to search.
.IP "\fItags\fP" 12
Tags to match against.
.IP "\fItag_count\fP" 12
Number of items in the tag list.

.SH RETURN VALUE
An array of renditions, \fItag_count\fP elements wide, with each index
corresponding to its counterpart in \fItags\fP. The resulting renditions
must be freed with \fBXmFreeRenditionArray\fP(3).

.SH SEE ALSO
\fBXmRenderTableGetRendition\fP(3), \fBXmFreeRenditionArray\fP(3)

.SH AUTHOR
Tim Hentenaar <tim@hentenaar.com>

\"vi:set ft=groff:
