.TH XMRENDERTABLEREMOVERENDITIONS 3 2026-09-16 "Motif 2.0"
.SH NAME
XmRenderTableRemoveRenditions - Remove renditions from a render table

.SH SYNOPSIS
.nf
#include <Xm/Xm.h>

\fBXmRenderTable XmRenderTableRemoveRenditions\fR(\fBXmRenderTable\fR oldtable,
\fB                                           \fR \fBXmStringTag *\fRtags,
\fB                                           \fR \fBint\fR tag_count);
.fi

.SH DESCRIPTION
Remove and free all renditions from a render table matching the given
tags. The non-matching renditions are moved to a newly-allocated
render table, and the original table is freed. If no tags are given, the
original table is returned unmodified.

.IP "\fItable\fP" 12
Render table to add to (or \fBNULL\fP).
.IP "\fItags\fP" 12
List of tags to remove.
.IP "\fItag_count\fP" 12
Number of tags in the list.

.SH RETURN VALUE
A newly-allocated render table containing the renditions from the given
table that did not match \fItags\fP. If all tags in the table matched
the list, \fBNULL\fP is returned. The returned table must be freed with
\fBXmRenderTableFree\fP(3).

.SH SEE ALSO
\fBXmRenderTableAddRenditions\fP(3), \fBXmRenderTableFree\fP(3)

.SH AUTHOR
Tim Hentenaar <tim@hentenaar.com>

\"vi:set ft=groff:
