.TH XMTEXTFIELDSETXMSTRING 3 2026-02-03 "Motif 2.5.3"
.SH NAME
XmTextFieldSetXmString - Set the compound string value of a TextField

.SH SYNOPSIS
.nf
#include <Xm/Xm.h>
.P
\fBvoid XmTextFieldSetXmString\fR(\fBWidget\fR w, \fBXmString\fR value);
.fi

.SH DESCRIPTION
Set the \fBXmString\fP value for the given \fBXmTextField\fP widget.

.IP "\fIw\fP" 12
\fBXmTextField\fP widget for which to get the value.
.IP "\fIvalue\fP" 12
\fBXmString\fP value to set.

.SH SEE ALSO
\fBXmTextFieldGetXmString\fP(3)

.SH AUTHOR
Tim Hentenaar <tim@hentenaar.com>

\"vi:set ft=groff:
