/**
 * Motif
 *
 * Copyright (c) 2026 Tim Hentenaar
 *
 * These libraries and programs are free software; you can
 * redistribute them and/or modify them under the terms of the GNU
 * Lesser General Public License as published by the Free Software
 * Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * These libraries and programs are distributed in the hope that
 * they will be useful, but WITHOUT ANY WARRANTY; without even the
 * implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 * PURPOSE. See the GNU Lesser General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with these librararies and programs; if not, write
 * to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
 * Floor, Boston, MA 02110-1301 USA
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include <X11/Intrinsic.h>

#include "XmCharI.h"

#define TABLE_SIZE 0x110000
#define MAX_DECOMP 5

#define MAX(X,Y) ((X) > (Y) ? (X) : (Y))

/* Linear properties table */
static struct codepoint_info table[TABLE_SIZE];

/* Decomposition map */
static XmCodepoint decomp_map[TABLE_SIZE][MAX_DECOMP];
static unsigned long n_decomp = 0;

/* Decomposition table */
static XmCodepoint *d_char = NULL;
static unsigned short d_chars = 1;

/* Composition map */
static struct comp_entry comp_map[TABLE_SIZE][MAX_DECOMP << 2];
static unsigned long n_comp = 0;

/* Composition table */
static struct comp_entry *c_table = NULL;
static unsigned short c_entries = 0;

/**
 * Customary multi-stage flattened trie (11:5:5)
 */
#define UCD_HI_SHIFT  10
#define UCD_HI_MASK   0x7ff
#define UCD_MID_SHIFT 5
#define UCD_MID_MASK  0x1f
#define UCD_LO_MASK   0x1f
#define UCD_MID_BLOCK_SIZE (UCD_MID_MASK + 1) /* Must be a power of 2 */
#define UCD_LO_BLOCK_SIZE  (UCD_LO_MASK  + 1) /* Must be a power of 2 */

static unsigned short ucd_hi[TABLE_SIZE >> UCD_HI_SHIFT]; /* 3rd-order index */
static unsigned short *ucd_mid = NULL;                    /* 2nd-order blocks */
static unsigned short *ucd_lo  = NULL;                    /* Blocks over ucd_props */
static struct codepoint_info **ucd_props = NULL;          /* unique property info  */
static unsigned long n_lo    = 0;
static unsigned long n_mid   = 0;
static unsigned long n_props = 1;

#define UCD_PROPS(X) ( \
    ucd_props[ \
        ucd_lo[ \
            ucd_mid[ \
                ucd_hi[ \
                    (i >> UCD_HI_SHIFT) & UCD_HI_MASK \
                ] * UCD_MID_BLOCK_SIZE + ((i >> UCD_MID_SHIFT) & UCD_MID_MASK) \
            ] * UCD_LO_BLOCK_SIZE + (i & UCD_LO_MASK) \
        ] \
    ] \
)

/**
 * Word break rules table
 */
static Boolean wb_table[WB_COUNT][WB_COUNT];

/**
 * Output file header
 */
static const char *header[] = {
"/****** NOTE: This file is autogenerated. Do not modify. **********/\n",
"\n/**\n",
" * Motif\n",
" *\n",
" * Copyright (c) 2026 Tim Hentenaar\n",
" *\n",
" * These libraries and programs are free software; you can\n",
" * redistribute them and/or modify them under the terms of the GNU\n",
" * Lesser General Public License as published by the Free Software\n",
" * Foundation; either version 2.1 of the License, or (at your option)\n",
" * any later version.\n",
" *\n",
" * These libraries and programs are distributed in the hope that\n",
" * they will be useful, but WITHOUT ANY WARRANTY; without even the\n",
" * implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR\n",
" * PURPOSE. See the GNU Lesser General Public License for more\n",
" * details.\n",
" *\n",
" * You should have received a copy of the GNU Lesser General Public\n",
" * License along with these librararies and programs; if not, write\n",
" * to the Free Software Foundation, Inc., 51 Franklin Street, Fifth\n",
" * Floor, Boston, MA 02110-1301 USA\n",
" */\n",
"\n#include <X11/Intrinsic.h>\n",
"\n#include \"XmCharI.h\"\n"
};

/**
 * List of UCD files to read properties from
 */
enum prop_file {
	DerivedCoreProperties = 0,
	DerivedLineBreak,
	DerivedNumericType,
	DerivedNormalizationProps,
	WordBreakProperty,
	EmojiData
};

#define N_PROP_FILES (EmojiData + 1)

static const char *prop_files[N_PROP_FILES] = {
	"DerivedCoreProperties.txt",
	"DerivedLineBreak.txt",
	"DerivedNumericType.txt",
	"DerivedNormalizationProps.txt",
	"WordBreakProperty.txt",
	"emoji-data.txt"
};

enum { /* Derived property line parsing states */
	BEGIN = 0,
	RANGE_START,
	RANGE_END,
	PROPERTY,
	EOL
};

enum { /* UnicodeData.txt parsing states */
	CODEPOINT = 1,
	CODEPOINT_DONE,
	COMBINING_CLASS = 4,
	COMBINING_CLASS_DONE,
	DECOMP_MAPPING,
	DECOMP_MAPPING_DONE,
	UD_EOL
};

enum { /* Property Types */
	DerivedProperty = 0,
	LineBreak,
	WordBreak,
	N_PROPTYPES
};

/**
 * Property strings to values
 */
struct prop_to_val {
	size_t len;
	const char *prop;
	unsigned long mask;
	unsigned long val;
} prop_to_val[N_PROPTYPES][MAX(MAX(LB_COUNT, WB_COUNT), PROP_COUNT) + 1] = {
{ /* DerivedProperty */
	{ 10, "Alphabetic",            ALNUM_MASK, AN_Alphabetic << ALNUM_SHIFT },
	{ 7,  "Numeric",               ALNUM_MASK, AN_Numeric    << ALNUM_SHIFT },
	{ 5,  "Digit",                 ALNUM_MASK, AN_Digit      << ALNUM_SHIFT },
	{ 7,  "Decimal",               ALNUM_MASK, AN_Decimal    << ALNUM_SHIFT },
	{ 9,  "Lowercase",             CASE_MASK,  CC_Lowercase  << CASE_SHIFT  },
	{ 9,  "Uppercase",             CASE_MASK,  CC_Uppercase  << CASE_SHIFT  },
	{ 21, "Extended_Pictographic", CP_ExtendedPictographic   << PROP_SHIFT, CP_ExtendedPictographic << PROP_SHIFT },
	{ 5,  "Emoji",                 CP_Emoji                  << PROP_SHIFT, CP_Emoji                << PROP_SHIFT },
	{ 18, "Emoji_Presentation",    CP_EmojiPresentation      << PROP_SHIFT, CP_EmojiPresentation    << PROP_SHIFT },
	{ 14, "Emoji_Modifier",        CP_EmojiModifier          << PROP_SHIFT, CP_EmojiModifier        << PROP_SHIFT },
	{ 19, "Emoji_Modifier_Base",   CP_EmojiModifierBase      << PROP_SHIFT, CP_EmojiModifierBase    << PROP_SHIFT },
	{ 15, "Emoji_Component",       CP_EmojiComponent         << PROP_SHIFT, CP_EmojiComponent       << PROP_SHIFT },
	{ 26, "Full_Composition_Exclusion", QC_MASK, QC_Exclusion << QC_SHIFT },
	{ 0, NULL, 0, 0 }
},

{ /* LineBreak */
	{ 2, "CR",  LB_MASK | WB_MASK, (LB_CR  << LB_SHIFT) | (WB_CR  << WB_SHIFT) },
	{ 2, "LF",  LB_MASK | WB_MASK, (LB_LF  << LB_SHIFT) | (WB_LF  << WB_SHIFT) },
	{ 3, "ZWJ", LB_MASK | WB_MASK, (LB_ZWJ << LB_SHIFT) | (WB_ZWJ << WB_SHIFT) },
	{ 2, "XX",  LB_MASK, LB_XX  << LB_SHIFT },
	{ 2, "BK",  LB_MASK, LB_BK  << LB_SHIFT },
	{ 2, "CM",  LB_MASK, LB_CM  << LB_SHIFT },
	{ 2, "GL",  LB_MASK, LB_GL  << LB_SHIFT },
	{ 2, "NL",  LB_MASK, LB_NL  << LB_SHIFT },
	{ 2, "SP",  LB_MASK, LB_SP  << LB_SHIFT },
	{ 2, "WJ",  LB_MASK, LB_WJ  << LB_SHIFT },
	{ 2, "ZW",  LB_MASK, LB_ZW  << LB_SHIFT },
	{ 2, "AI",  LB_MASK, LB_AI  << LB_SHIFT },
	{ 2, "AK",  LB_MASK, LB_AK  << LB_SHIFT },
	{ 2, "AL",  LB_MASK, LB_AL  << LB_SHIFT },
	{ 2, "AP",  LB_MASK, LB_AP  << LB_SHIFT },
	{ 2, "AS",  LB_MASK, LB_AS  << LB_SHIFT },
	{ 2, "B2",  LB_MASK, LB_B2  << LB_SHIFT },
	{ 2, "BA",  LB_MASK, LB_BA  << LB_SHIFT },
	{ 2, "BB",  LB_MASK, LB_BB  << LB_SHIFT },
	{ 2, "CB",  LB_MASK, LB_CB  << LB_SHIFT },
	{ 2, "CJ",  LB_MASK, LB_CJ  << LB_SHIFT },
	{ 2, "CL",  LB_MASK, LB_CL  << LB_SHIFT },
	{ 2, "CP",  LB_MASK, LB_CP  << LB_SHIFT },
	{ 2, "EB",  LB_MASK, LB_EB  << LB_SHIFT },
	{ 2, "EM",  LB_MASK, LB_EM  << LB_SHIFT },
	{ 2, "EX",  LB_MASK, LB_EX  << LB_SHIFT },
	{ 2, "H2",  LB_MASK, LB_H2  << LB_SHIFT },
	{ 2, "H3",  LB_MASK, LB_H3  << LB_SHIFT },
	{ 2, "HH",  LB_MASK, LB_HH  << LB_SHIFT },
	{ 2, "HL",  LB_MASK, LB_HL  << LB_SHIFT },
	{ 2, "HY",  LB_MASK, LB_HY  << LB_SHIFT },
	{ 2, "ID",  LB_MASK, LB_ID  << LB_SHIFT },
	{ 2, "IN",  LB_MASK, LB_IN  << LB_SHIFT },
	{ 2, "IS",  LB_MASK, LB_IS  << LB_SHIFT },
	{ 2, "JL",  LB_MASK, LB_JL  << LB_SHIFT },
	{ 2, "JT",  LB_MASK, LB_JT  << LB_SHIFT },
	{ 2, "JV",  LB_MASK, LB_JV  << LB_SHIFT },
	{ 2, "NS",  LB_MASK, LB_NS  << LB_SHIFT },
	{ 2, "NU",  LB_MASK, LB_NU  << LB_SHIFT },
	{ 2, "OP",  LB_MASK, LB_OP  << LB_SHIFT },
	{ 2, "PO",  LB_MASK, LB_PO  << LB_SHIFT },
	{ 2, "PR",  LB_MASK, LB_PR  << LB_SHIFT },
	{ 2, "QU",  LB_MASK, LB_QU  << LB_SHIFT },
	{ 2, "RI",  LB_MASK, LB_RI  << LB_SHIFT },
	{ 2, "SA",  LB_MASK, LB_SA  << LB_SHIFT },
	{ 2, "SY",  LB_MASK, LB_SY  << LB_SHIFT },
	{ 2, "VF",  LB_MASK, LB_VF  << LB_SHIFT },
	{ 2, "VI",  LB_MASK, LB_VI  << LB_SHIFT },
	{ 0, NULL, 0, 0 }
},

{ /* WordBreak */
	{ 7,  "Newline",            WB_MASK, WB_Newline            << WB_SHIFT },
	{ 6,  "Extend",             WB_MASK, WB_Extend             << WB_SHIFT },
	{ 18, "Regional_Indicator", WB_MASK, WB_Regional_Indicator << WB_SHIFT },
	{ 6,  "Format",             WB_MASK, WB_Format             << WB_SHIFT },
	{ 8,  "Katakana",           WB_MASK, WB_Katakana           << WB_SHIFT },
	{ 13, "Hebrew_Letter",      WB_MASK, WB_Hebrew_Letter      << WB_SHIFT },
	{ 7,  "ALetter",            WB_MASK, WB_ALetter            << WB_SHIFT },
	{ 12, "Single_Quote",       WB_MASK, WB_SingleQuote        << WB_SHIFT },
	{ 12, "Double_Quote",       WB_MASK, WB_DoubleQuote        << WB_SHIFT },
	{ 9,  "MidNumLet",          WB_MASK, WB_MidNumLet          << WB_SHIFT },
	{ 9,  "MidLetter",          WB_MASK, WB_MidLetter          << WB_SHIFT },
	{ 6,  "MidNum",             WB_MASK, WB_MidNum             << WB_SHIFT },
	{ 7,  "Numeric",            WB_MASK, WB_Numeric            << WB_SHIFT },
	{ 12, "ExtendNumLet",       WB_MASK, WB_ExtendNumLet       << WB_SHIFT },
	{ 9,  "WSegSpace",          WB_MASK, WB_WSegSpace          << WB_SHIFT },
	{ 0, NULL, 0, 0 }
}};

/**
 * Quick Check state transition table
 */
static const enum quick_check_props qc_table[3][QC_LEN] = {
{ /* NFD_QC=N */
	QC_Precomposed, QC_BackwardDecomp, QC_Exclusion,
	QC_Exclusion, QC_Exclusion
},
{ /* NFC_QC=M */
	QC_BackwardCombine, QC_BackwardCombine, QC_BackwardDecomp,
	QC_BackwardDecomp, QC_BackwardDecomp
},
{ /* NFC_QC=N */
	QC_Exclusion, QC_Standard, QC_Exclusion,
	QC_Exclusion, QC_BackwardDecomp
}};

/**
 * Apply a Unicode property to a codepoint
 */
static void apply_prop(enum prop_file file, const char *line,
                       unsigned long codepoint, unsigned long start)
{
	unsigned int i, idx = DerivedProperty;
	unsigned long val = 0;
	const char *s = line;
	size_t len = 0;

	/**
	 * The remainder of the relevant part of the line is formatted like:
	 *   Simple case: "Property #"
	 *   Other cases: "Property; value #"
	 *
	 * Ensure it ain't too short.
	 */
	while (*s && *s != '#') s++;
	if (!(len = s - line - 1) || (len == 1 && *s == ' '))
		return;

	/* emoji-data:Extended_Pictographic omits the customary space before '#' */
	if (line[len] != ' ')
		len++;

	/* Map to the corresponding property set */
	if (file == DerivedLineBreak)       idx = LineBreak;
	else if (file == WordBreakProperty) idx = WordBreak;

	/* Fill in decimal values */
	if (len == 7 && !memcmp(line, "Decimal", 7) && file == DerivedNumericType)
		table[codepoint].props = (table[codepoint].props & ~DECIMAL_MASK) | ((codepoint - start) & DECIMAL_MASK);

	/* Normalization Quick Check values */
	if (len == 9 && file == DerivedNormalizationProps) {
		if ((val = (table[codepoint].props & QC_MASK) >> QC_SHIFT) == QC_Exclusion)
			return;

		if (!memcmp(line, "NFD_QC; N", 9))
			val = qc_table[0][val];
		else if (!memcmp(line, "NFC_QC; ", 8))
			val = qc_table[(line[8] != 'M') + 1][val];

		table[codepoint].props = (table[codepoint].props & ~QC_MASK) | (val << QC_SHIFT);
		return;
	}

	/* Simple cases */
	for (i = 0; i < sizeof(prop_to_val[idx]) / sizeof *prop_to_val[idx]; i++) {
		if (!prop_to_val[idx][i].len)
			break;

		if (len == prop_to_val[idx][i].len && !memcmp(line, prop_to_val[idx][i].prop, len)) {
			table[codepoint].props = (table[codepoint].props & ~prop_to_val[idx][i].mask) | prop_to_val[idx][i].val;
			return;
		}
	}
}

/**
 * Simple routine to add derived properties to the table for each
 * codepoint / range of codepoints given. Malformed lines are simply
 * skipped after emitting an "ERROR" message.
 */
static void parse_ucd_line(enum prop_file file, int linenum, char *line)
{
	unsigned int state = BEGIN, pos = 0, ch, i, j, stack[6];
	unsigned long range_start, range_end, cp;

	do {
		ch = *line++;
		pos++;

		/* Ignore comments / empty lines */
		if (ch == '\0' || ch == '\r' || ch == '\n' || ch == '#')
			break;

		switch (state) {
		case BEGIN: /* Start of a line */
			if ((ch >= '0' && ch <= '9') ||
			    (ch >= 'a' && ch <= 'f') ||
			    (ch >= 'A' && ch <= 'F')) {
			    i = range_start = range_end = 0;
				state = RANGE_START;
				line--;
				pos--;
				break;
			}

			fprintf(stderr, "ERROR: %s:%d:%u codepoint range expected\n",
			        prop_files[file], linenum, pos);
			state = EOL;
			break;
		case RANGE_START: /* Start / End of a codepoint / codepoint range */
		case RANGE_END:
			if (ch == '.') {
				if (state == RANGE_END)
					break;

				if (!i) {
					fprintf(stderr,
					        "ERROR: %s:%d:%u '.' without starting "
					        "value for codepoint range\n",
					        prop_files[file], linenum, pos);
					 state = EOL;
					 break;
				}

				range_end = 0;
				state     = RANGE_END;
				for (j = 1; i > 0; --i, j *= 16)
					range_start += stack[i - 1] * j;
				break;
			}

			/* Wait for ';' */
			if (ch == ' ')
				break;

			if (ch == ';') {
				if (!i) {
					fprintf(stderr,
					        "ERROR: %s:%d:%u ';' Expected codepoint range\n",
					        prop_files[file], linenum, pos);
					 state = EOL;
					 break;
				}

				for (j = 1; i > 0; --i, j *= 16) {
					if (state == RANGE_START)
						range_start += stack[i - 1] * j;
					else range_end += stack[i - 1] * j;
				}

				/* Single value */
				if (state == RANGE_START)
					range_end = range_start;
				state = PROPERTY;
				break;
			}

			if (i >= sizeof(stack) / sizeof(unsigned int)) {
				fprintf(stderr,
				        "ERROR: %s:%d:%u Hex value too large\n",
				        prop_files[file], linenum, pos);
				 state = EOL;
				 break;
			}

			if (ch >= '0' && ch <= '9')      stack[i++] = ch - '0';
			else if (ch >= 'a' && ch <= 'f') stack[i++] = 10 + (ch - 'a');
			else if (ch >= 'A' && ch <= 'F') stack[i++] = 10 + (ch - 'A');
			else {
				fprintf(stderr,
				        "ERROR: %s:%d:%u Expected hex digit for codepoint (got %c)\n",
				        prop_files[file], linenum, pos, ch);
				 state = EOL;
			}
			break;
		case PROPERTY: /* Property to apply to the given range */
			if (range_start >= TABLE_SIZE) {
				fprintf(stderr,
				        "ERROR: %s:%d:%u Range start (%06lX) exceeds TABLE_SIZE\n",
				        prop_files[file], linenum, pos, range_start);
				state = EOL;
				break;
			}

			if (range_end >= TABLE_SIZE) {
				fprintf(stderr,
				        "ERROR: %s:%d:%u Range end (%06lX) exceeds TABLE_SIZE\n",
				        prop_files[file], linenum, pos, range_end);
				state = EOL;
				break;
			}

			if (range_end < range_start) {
				fprintf(stderr,
				        "ERROR: %s:%d:%u Range start (%06lX) exceeds end (%lX)\n",
				        prop_files[file], linenum, pos, range_start, range_end);
				state = EOL;
				break;
			}

			for (cp = range_start; cp <= range_end; cp++)
				apply_prop(file, line, cp, range_start);

			state = EOL;
			break;
		}
	} while (state != EOL);
}

/**
 * Find a slot in our composition map, and populate it.
 *
 * A + B = C
 */
static void add_composition(unsigned long a, unsigned long b, unsigned long c)
{
	unsigned int i;

	for (i = 0; i < sizeof comp_map[0] / sizeof comp_map[0][0]; i++) {
		if (comp_map[a][i].result)
			continue;

		comp_map[a][i].comb   = b;
		comp_map[a][i].result = c;
		++n_comp;
		return;
	}

	fprintf(stderr, "WARNING: Could not find a free slot to add the "
	        "composition (0x%06lX + 0x%06lX --> 0x%06lX)\n",
	        a, b, c);
}

static void parse_unicode_data(int linenum, char *line)
{
	unsigned int state = BEGIN, pos = 0, ch, i = 0, j, k = 0, stack[6];
	unsigned int ccc = UINT_MAX;
	unsigned long cp = ULONG_MAX;

	do {
		ch = *line++;
		pos++;

		if (ch == ';') {
			state++;
			ch = *line++;
			pos++;
		}

		/* Ignore comments / empty lines */
		if (ch == '\0' || ch == '\r' || ch == '\n' || ch == '#')
			break;

		switch (state) {
		case BEGIN: /* Start of a line */
			if ((ch >= '0' && ch <= '9') ||
			    (ch >= 'a' && ch <= 'f') ||
			    (ch >= 'A' && ch <= 'F')) {
			    i     = 0;
			    ccc   = UINT_MAX;
			    cp    = ULONG_MAX;
				state = CODEPOINT;
				line--;
				pos--;
				break;
			}

			fprintf(stderr, "ERROR: UnicodeData.txt:%d:%u codepoint expected\n",
			        linenum, pos);
			state = UD_EOL;
			break;
		case CODEPOINT:
			if (ch >= '0' && ch <= '9')      stack[i++] = ch - '0';
			else if (ch >= 'a' && ch <= 'f') stack[i++] = 10 + (ch - 'a');
			else if (ch >= 'A' && ch <= 'F') stack[i++] = 10 + (ch - 'A');
			else {
				fprintf(stderr,
				        "ERROR: UnicodeData.txt:%d:%u Expected hex digit for codepoint (got %c)\n",
				        linenum, pos, ch);
				 state = UD_EOL;
			}
			break;
		case CODEPOINT_DONE:
			if (cp != ULONG_MAX)
				continue;

			cp = 0;
			for (j = 1; i > 0; --i, j *= 16)
				cp += stack[i - 1] * j;

			if (cp > TABLE_SIZE) {
				fprintf(stderr,
				        "ERROR: UnicodeData.txt:%d:%u codepoint value out of range\n",
				        linenum, pos);
				 state = UD_EOL;
			}
			break;
		case COMBINING_CLASS:
			if (ch < '0' || ch > '9') {
				fprintf(stderr,
				        "ERROR: UnicodeData.txt:%d:%u Expected digit for ccc (got %c)\n",
				        linenum, pos, ch);
				 state = UD_EOL;
				 break;
			}

			stack[i++] = ch - '0';
			break;
		case COMBINING_CLASS_DONE:
			if (ccc != UINT_MAX)
				continue;

			ccc = 0;
			for (j = 1; i > 0; --i, j *= 10)
				ccc += stack[i - 1] * j;

			if (ccc > UCHAR_MAX) {
				fprintf(stderr,
				        "ERROR: UnicodeData.txt:%d:%u ccc value out of range\n",
				        linenum, pos);
				 state = UD_EOL;
				 break;
			}

			k = 0;
			table[cp].ccc = ccc & 0xff;
			break;
		case DECOMP_MAPPING: /* codepoint [...] */
			if (ch == ';')
				break;

			if (ch == '<') { /* Ignore compatibility mappings */
				state = UD_EOL;
				break;
			}

			if (ch == ' ') {
				if (k >= MAX_DECOMP) {
					fprintf(stderr,
					        "ERROR: UnicodeData.txt:%d:%u Too many decomp "
					        "map entries for U+%06lX\n", linenum, pos, cp);
					state = UD_EOL;
					break;
				}

				decomp_map[cp][k] = 0;
				for (j = 1; i > 0; --i, j *= 16)
					decomp_map[cp][k] += stack[i - 1] * j;
				table[decomp_map[cp][k]].props |= k ? CB_MASK : CF_MASK;
				++k;
				++n_decomp;
				break;
			}

			if (ch >= '0' && ch <= '9')      stack[i++] = ch - '0';
			else if (ch >= 'a' && ch <= 'f') stack[i++] = 10 + (ch - 'a');
			else if (ch >= 'A' && ch <= 'F') stack[i++] = 10 + (ch - 'A');
			else {
				fprintf(stderr,
				        "ERROR: UnicodeData.txt:%d:%u Expected hex digit for decomp codepoint\n",
				        linenum, pos);
				 state = UD_EOL;
			}

			break;
		case DECOMP_MAPPING_DONE:
			if (k >= MAX_DECOMP) {
				fprintf(stderr,
				        "ERROR: UnicodeData.txt:%d:%u Too many decomp "
				        "map entries for U+%06lX\n", linenum, pos, cp);
				state = UD_EOL;
				break;
			}

			/* Mapping was empty */
			if (!i && !k)
				break;

			decomp_map[cp][k] = 0;
			if (i) {
				/* We'll boil these down in the 2nd pass */
				for (j = 1; i > 0; --i, j *= 16)
					decomp_map[cp][k] += stack[i - 1] * j;

				/* Set combining flags */
				table[cp].props |= CF_MASK;
				table[decomp_map[cp][k]].props |= k ? CB_MASK : CF_MASK;
				++k;
				++n_decomp;
			}

			/* Ignore codepoints excluded from composition */
			if (((table[cp].props & QC_MASK) >> QC_SHIFT) == QC_Exclusion) {
				state = UD_EOL;
				break;
			}

			/* Singletons can't be re-composed */
			if (k == 2 && decomp_map[cp][1])
				add_composition(decomp_map[cp][0], decomp_map[cp][1], cp);

			state = UD_EOL;
			break;
		}
	} while (state != UD_EOL);
}

/**
 * Recursively compute the final decomposition state for a given
 * character, allowing for an O(1) lookup at runtime.
 */
static XmCodepoint *decompose(XmCodepoint cp, XmCodepoint *out, unsigned int *n)
{
	unsigned int i = 0;

	if (!(out = realloc(out, sizeof *out * (*n + 1)))) {
		fputs("decompose: Out of memory", stderr);
		exit(EXIT_FAILURE);
	}

	/* Use the character if we've hit the ultimate leaf node */
	if (!decomp_map[cp][0]) {
		out[*n] = cp;
		++*n;
		return out;
	}

	if (decomp_map[cp][0] == cp) {
		fprintf(stderr, "ERROR: decompose: Cycle found cp=0x%06lX",
		        (unsigned long)cp);
		out[*n] = cp;
		++*n;
		return out;
	}

	/* Find the ultimate leaf nodes for each codepoint */
	for (i = 0; i < MAX_DECOMP && decomp_map[cp][i]; i++)
		out = decompose(decomp_map[cp][i], out, n);
	return out;
}

/**
 * Finalize decomposition sequences and generate the decomposition
 * table.
 */
static void finalize_decomp(void)
{
	unsigned int flen;
	unsigned short idx = 0;
	unsigned long i, j = n_decomp;
	XmCodepoint *tmp = NULL;

	for (i = 0; j && i < TABLE_SIZE; i++) {
		if (!decomp_map[i][0] || decomp_map[i][0] == i)
			continue;

		flen = 0;
		tmp  = decompose(i, NULL, &flen);

		if (!(d_char = realloc(d_char, sizeof *d_char * (d_chars + flen)))) {
			fputs("finalize_decomp: Out of memory", stderr);
			exit(EXIT_FAILURE);
		}

		table[i].decomp   = d_chars;
		table[i].n_decomp = flen;
		memcpy(d_char + d_chars, tmp, flen * sizeof *d_char);
		d_chars += flen;
		free(tmp);
		--j;
	}

	if (d_char)
		d_char[0] = 0;
}

/**
 * Finalize composition sequences and create the final table.
 */
static void finalize_comp(void)
{
	unsigned int i, k, j = n_comp;

	for (i = 0; j && i < TABLE_SIZE; i++) {
		if (!comp_map[i][0].result)
			continue;

		/* Determine how many we need to add */
		for (k = 0; k < sizeof comp_map[0] / sizeof comp_map[0][0]; k++) {
			if (!comp_map[i][k].result)
				break;
		}

		if (!(c_table = realloc(c_table, sizeof *c_table * (c_entries + k + 1)))) {
			fputs("finalize_comp: Out of memory", stderr);
			exit(EXIT_FAILURE);
		}

		/* Add the entries and update the main table */
		table[i].n_comp = k;
		table[i].comp   = c_entries;
		memcpy(c_table + c_entries, comp_map[i], k * sizeof *c_table);
		c_entries += k;
		--j;
	}
}

/**
 * Construct a multi-stage table by grouping unique properties
 * values, as recommended by the Unicode standard, into unique blocks
 * in a single pass over the full table.
 */
static void finalize_table(void)
{
	unsigned long b = 0, i, n, j, n_uniq = 1;
	unsigned short *uniq_props;
	unsigned short *uniq_lo;

	/* Dedup props */
	n_props = 0;
	if (!(uniq_props = calloc(TABLE_SIZE, sizeof *uniq_props))) {
		fprintf(stderr, "Failed to allocate unique props index array\n");
		exit(EXIT_FAILURE);
	}

	for (n = 0; n < TABLE_SIZE; n++) {
		for (i = 0; i < n_props; i++) {
			if (!memcmp(ucd_props[i], table + n, sizeof *table)) {
				uniq_props[n] = i & 0xffff;
				break;
			}
		}

		if (i == n_props) {
			uniq_props[n] = i & 0xffff;
			if (!(ucd_props = realloc(ucd_props, ++n_props * sizeof *ucd_props))) {
				fprintf(stderr, "Failed to enlarge the props pointer table\n");
				exit(EXIT_FAILURE);
			}

			if (n_props >= USHRT_MAX) {
				fprintf(stderr, "Too many unique props (%lu)\n", n_props);
				exit(EXIT_FAILURE);
			}

			ucd_props[i] = table + n;
		}
	}

	/* Unique blocks over unique props */
	if (!(uniq_lo = calloc(TABLE_SIZE / UCD_LO_BLOCK_SIZE, sizeof *uniq_lo))) {
		fprintf(stderr, "Failed to allocate unique lo index array\n");
		exit(EXIT_FAILURE);
	}

	n_lo = 0;
	for (n = 0; n < TABLE_SIZE; n += UCD_LO_BLOCK_SIZE) {
		for (i = 0; i < n_lo; i++) {
			if (!memcmp(ucd_lo + i * UCD_LO_BLOCK_SIZE, uniq_props + n, UCD_LO_BLOCK_SIZE * sizeof *ucd_lo))
				break;
		}

		if (i == n_lo) {
			if (!(ucd_lo = realloc(ucd_lo, ++n_lo * UCD_LO_BLOCK_SIZE * sizeof *ucd_lo))) {
				fprintf(stderr, "Failed to allocate memory for the lo array\n");
				exit(EXIT_FAILURE);
			}

			memcpy(ucd_lo + i * UCD_LO_BLOCK_SIZE, uniq_props + n, UCD_LO_BLOCK_SIZE * sizeof *ucd_lo);
		}

		uniq_lo[n / UCD_LO_BLOCK_SIZE] = i;
	}
	free(uniq_props);

	/* Unique 2nd-order blocks */
	n_mid = 0;
	for (n = 0; n < TABLE_SIZE / UCD_LO_BLOCK_SIZE; n += UCD_MID_BLOCK_SIZE) {
		for (i = 0; i < n_mid; i++) {
			if (!memcmp(ucd_mid + i * UCD_MID_BLOCK_SIZE, uniq_lo + n, UCD_MID_BLOCK_SIZE * sizeof *ucd_mid))
				break;
		}

		if (i == n_mid) {
			if (!(ucd_mid = realloc(ucd_mid, ++n_mid * UCD_MID_BLOCK_SIZE * sizeof *ucd_mid))) {
				fprintf(stderr, "Failed to allocate memory for the mid array\n");
				exit(EXIT_FAILURE);
			}

			memcpy(ucd_mid + i * UCD_MID_BLOCK_SIZE, uniq_lo + n, UCD_MID_BLOCK_SIZE * sizeof *ucd_mid);
		}

		ucd_hi[n / UCD_MID_BLOCK_SIZE] = i;
	}

	free(uniq_lo);
}

static void make_wb_table(void)
{
	enum word_break_props i, j;

	/* WB999: Break everywhere by default */
	for (i = 0; i < WB_COUNT; i++) {
		for (j = 0; j < WB_COUNT; j++) {
			wb_table[i][j] = True;
		}

		/* WB4: Any × (Format | Extend | ZWJ) */
		wb_table[i][WB_Format] = False;
		wb_table[i][WB_Extend] = False;
		wb_table[i][WB_ZWJ]    = False;
	}

	/* WB3: No break between CR + LF */
	wb_table[WB_CR][WB_LF] = False;

	/* WB3d: No break between WSegSpace x WSegSpace */
	wb_table[WB_WSegSpace][WB_WSegSpace] = False;

	/* WB5: Do not break between most letters */
	wb_table[WB_ALetter][WB_ALetter]             = False;
	wb_table[WB_ALetter][WB_Hebrew_Letter]       = False;
	wb_table[WB_Hebrew_Letter][WB_Hebrew_Letter] = False;
	wb_table[WB_Hebrew_Letter][WB_ALetter]       = False;

	/* WB6 - 7c: Don't break across certain punctuation */
	wb_table[WB_ALetter][WB_MidLetter]         = False;
	wb_table[WB_ALetter][WB_MidNumLet]         = False;
	wb_table[WB_ALetter][WB_SingleQuote]       = False;
	wb_table[WB_Hebrew_Letter][WB_MidLetter]   = False;
	wb_table[WB_Hebrew_Letter][WB_MidNumLet]   = False;
	wb_table[WB_Hebrew_Letter][WB_SingleQuote] = False;
	wb_table[WB_MidLetter][WB_ALetter]         = False;
	wb_table[WB_MidLetter][WB_Hebrew_Letter]   = False;
	wb_table[WB_MidNumLet][WB_ALetter]         = False;
	wb_table[WB_MidNumLet][WB_Hebrew_Letter]   = False;
	wb_table[WB_SingleQuote][WB_ALetter]       = False;
	wb_table[WB_SingleQuote][WB_Hebrew_Letter] = False;
	wb_table[WB_Hebrew_Letter][WB_SingleQuote] = False;
	wb_table[WB_Hebrew_Letter][WB_DoubleQuote] = False;
	wb_table[WB_DoubleQuote][WB_Hebrew_Letter] = False;

	/**
	 * WB8 - 10: Don't break within digit sequences or digits adjacent
	 * to letters
	 */
	wb_table[WB_Numeric][WB_Numeric]       = False;
	wb_table[WB_ALetter][WB_Numeric]       = False;
	wb_table[WB_Hebrew_Letter][WB_Numeric] = False;
	wb_table[WB_Numeric][WB_ALetter]       = False;
	wb_table[WB_Numeric][WB_Hebrew_Letter] = False;

	/* WB11 - 12: Don't break within sequences like "3.2" */
	wb_table[WB_MidNum][WB_Numeric]      = False;
	wb_table[WB_MidNumLet][WB_Numeric]   = False;
	wb_table[WB_SingleQuote][WB_Numeric] = False;
	wb_table[WB_Numeric][WB_MidNum]      = False;
	wb_table[WB_Numeric][WB_MidNumLet]   = False;
	wb_table[WB_Numeric][WB_SingleQuote] = False;

	/* WB13: Don't break between Katakana */
	wb_table[WB_Katakana][WB_Katakana] = False;

	/* WB13a - b: Don't break from extenders */
	wb_table[WB_ALetter][WB_ExtendNumLet]       = False;
	wb_table[WB_Hebrew_Letter][WB_ExtendNumLet] = False;
	wb_table[WB_Numeric][WB_ExtendNumLet]       = False;
	wb_table[WB_Katakana][WB_ExtendNumLet]      = False;
	wb_table[WB_ExtendNumLet][WB_ExtendNumLet]  = False;
	wb_table[WB_ExtendNumLet][WB_ALetter]       = False;
	wb_table[WB_ExtendNumLet][WB_Hebrew_Letter] = False;
	wb_table[WB_ExtendNumLet][WB_Numeric]       = False;
	wb_table[WB_ExtendNumLet][WB_Katakana]      = False;

	/**
	 * WB15 - 16: Don't break within emoji flag sequences
	 *
	 * Since we're only looking at two adjacent codepoints, we'll
	 * generalize this to mean RI x RI since we don't know how many
	 * RI preceed what we're looking at.
	 */
	wb_table[WB_Regional_Indicator][WB_Regional_Indicator] = False;
}

/**
 * Write the tables to the output file.
 */
static void write_file(const char *filename)
{
	FILE *fp;
	unsigned int i, j;

	if (!(fp = fopen(filename, "w+"))) {
		fprintf(stderr, "ERROR: Failed to open %s for writing\n", filename);
		exit(EXIT_FAILURE);
	}

	for (i = 0; i < sizeof header / sizeof *header; i++)
		fputs(header[i], fp);

	fprintf(fp, "\n#define UCD_HI_MASK         0x%x\n", UCD_HI_MASK);
	fprintf(fp, "#define UCD_HI_SHIFT        %u\n", UCD_HI_SHIFT);
	fprintf(fp, "#define UCD_MID_MASK        0x%x\n", UCD_MID_MASK);
	fprintf(fp, "#define UCD_MID_SHIFT       %u\n", UCD_MID_SHIFT);
	fprintf(fp, "#define UCD_LO_MASK         0x%x\n", UCD_LO_MASK);
	fprintf(fp, "#define UCD_MID_BLOCK_SIZE  %u\n", UCD_MID_BLOCK_SIZE);
	fprintf(fp, "#define UCD_LO_BLOCK_SIZE   %u\n", UCD_LO_BLOCK_SIZE);
	fputs("#define UCD_PROPS(X) ( \\\n"
	      "\tucd_props[ \\\n"
	      "\t\tucd_lo[ \\\n"
	      "\t\t\tucd_mid[ \\\n"
	      "\t\t\t\tucd_hi[ \\\n"
	      "\t\t\t\t\t((X) >> UCD_HI_SHIFT) & UCD_HI_MASK \\\n"
	      "\t\t\t\t] * UCD_MID_BLOCK_SIZE + (((X) >> UCD_MID_SHIFT) & UCD_MID_MASK) \\\n"
	      "\t\t\t] * UCD_LO_BLOCK_SIZE + ((X) & UCD_LO_MASK) \\\n"
	      "\t\t] \\\n"
	      "\t] \\\n)", fp);

	/* Props */
	fprintf(fp, "\nstatic const unsigned short ucd_hi[%lu] = {\n\t",
	        sizeof ucd_hi / sizeof *ucd_hi);

	for (i = 0; i < sizeof ucd_hi / sizeof *ucd_hi; i++) {
		if (i) {
			fputc(',', fp);
			if (!(i & 7)) {
				fputc('\n', fp);
				fputc('\t', fp);
			} else fputc(' ', fp);
		}

		fprintf(fp, "0x%04x", ucd_hi[i]);
	}
	fputs("\n};\n", fp);

	fprintf(fp, "\nstatic const unsigned short ucd_mid[%lu] = {\n\t", n_mid * UCD_MID_BLOCK_SIZE);
	for (i = 0; i < n_mid * UCD_MID_BLOCK_SIZE; i++) {
		if (i) {
			fputc(',', fp);
			if (!(i & 7)) {
				fputc('\n', fp);
				fputc('\t', fp);
			} else fputc(' ', fp);
		}

		fprintf(fp, "0x%04x", ucd_mid[i]);
	}
	fputs("\n};\n", fp);


	fprintf(fp, "\nstatic const unsigned short ucd_lo[%lu] = {\n\t", n_lo * UCD_LO_BLOCK_SIZE);
	for (i = 0; i < n_lo * UCD_LO_BLOCK_SIZE; i++) {
		if (i) {
			fputc(',', fp);
			if (!(i & 7)) {
				fputc('\n', fp);
				fputc('\t', fp);
			} else fputc(' ', fp);
		}

		fprintf(fp, "0x%04x", ucd_lo[i]);
	}
	fputs("\n};\n", fp);

	fprintf(fp, "\nstatic const struct codepoint_info ucd_props[%lu] = {\n", n_props);
	for (i = 0; i < n_props; i++) {
		if (i) {
			fputc(',', fp);
			fputc('\n', fp);
		}

		fprintf(fp, "\t{ 0x%08x, %u, %u, %u, %u, %u }",
		        ucd_props[i]->props, ucd_props[i]->ccc, ucd_props[i]->n_comp,
		        ucd_props[i]->n_decomp, ucd_props[i]->comp,
		        ucd_props[i]->decomp);
	}
	fputs("\n};\n", fp);

	/* Composition table */
	fprintf(fp, "\nstatic const struct comp_entry comp_table[%u] = {\n", c_entries);
	for (i = 0; i < c_entries; i++) {
		if (i) {
			fputc(',', fp);
			fputc('\n', fp);
		}

		fprintf(fp, "\t{ 0x%06x, 0x%06x }", c_table[i].comb, c_table[i].result);
	}
	fputs("\n};\n", fp);

	/* Decomposition table */
	fprintf(fp, "\nstatic const XmCodepoint decomp_table[%u] = {\n\t", d_chars);
	for (i = 0; i < d_chars; i++) {
		if (i) {
			fputc(',', fp);
			if (!(i % 7)) {
				fputc('\n', fp);
				fputc('\t', fp);
			} else fputc(' ', fp);
		}

		fprintf(fp, "0x%06x", d_char[i]);
	}
	fputs("\n};\n", fp);

	/* Word break table */
	fprintf(fp, "\nstatic const Boolean wb_table[%u][%u] = {\n", WB_COUNT, WB_COUNT);
	for (i = 0; i < WB_COUNT; i++) {
		if (i) {
			fputc(',', fp);
			fputc('\n', fp);
		}

		fputc('\t', fp);
		fputc('{', fp);
		fputc(' ', fp);
		for (j = 0; j < WB_COUNT; j++) {
			if (j) {
				fputc(',', fp);
				if (!(j % 10)) {
					fputc('\n', fp);
					fputc('\t', fp);
					fputc(' ', fp);
					fputc(' ', fp);
				} else fputc(' ', fp);
			}

			fprintf(fp, "%s", wb_table[i][j] ? "True" : "False");
		}
		fputc(' ', fp);
		fputc('}', fp);
	}

	fputs("\n};\n", fp);
	fflush(fp);
	fclose(fp);
}

int main(int argc, char *argv[])
{
	FILE *fp;
	size_t n, i;
	int linenum;
	char buf[BUFSIZ];
	enum prop_file p;

	/* The sole argument is the path to write the generated header to */
	if (argc != 2) {
		fprintf(stderr, "Usage: %s /path/to/header.h\n", argv[0]);
		exit(EXIT_FAILURE);
	}

	/* Process property files linewise */
	memset(table, 0, sizeof table);
	for (p = 0; p < N_PROP_FILES; p++) {
		linenum = 1;
		printf("Consuming %s...\n", prop_files[p]);
		fflush(stdout);
		if (!(fp = fopen(prop_files[p], "rb"))) {
			fprintf(stderr, "Failed to open %s\n", prop_files[p]);
			continue;
		}

		while (fgets(buf, sizeof buf, fp))
			parse_ucd_line(p, linenum++, buf);
		fclose(fp);
		fflush(stdout);
	}

	/* Populate [de-]composition info (UnicodeData.txt) */
	memset(decomp_map, 0, sizeof decomp_map);
	memset(comp_map, 0, sizeof comp_map);
	if (!(fp = fopen("UnicodeData.txt", "rb"))) {
		fputs("Failed to open UnicodeData.txt", stderr);
		exit(EXIT_FAILURE);
	}

	linenum = 1;
	puts("Consuming UnicodeData.txt...");
	fflush(stdout);
	while (fgets(buf, sizeof buf, fp))
		parse_unicode_data(linenum++, buf);
	fclose(fp);
	fflush(stdout);

	finalize_comp();
	printf("Composition table size: %lu bytes / %u entries\n",
	        c_entries * sizeof *c_table, c_entries);
	fflush(stdout);

	finalize_decomp();
	printf("Decomposition table size: %lu bytes / %u codepoints\n",
	       d_chars * sizeof *d_char, d_chars - 1);

	/* Compress our big, beautiful table into a multi-stage table */
	printf("Flat table size: %lu bytes\n", sizeof table);
	fflush(stdout);

	finalize_table();
	printf("Prepared table: %lu unique props, %lu unique blocks, %lu 2nd-order blocks\n",
	       n_props, n_lo, n_mid);
	printf("Approximate size: %lu bytes\n",
	       n_props * sizeof *ucd_props + n_lo * UCD_LO_BLOCK_SIZE * sizeof *ucd_lo +
	       n_mid * UCD_MID_BLOCK_SIZE * sizeof *ucd_mid + sizeof ucd_hi);

	/* Sanity check */
	fflush(stdout);
	for (i = 0; i < TABLE_SIZE; i++) {
		if (memcmp(table + i, UCD_PROPS(i), sizeof *table)) {
			fprintf(stderr, "Table mismatch: U+%06lX doesn't match\n", i);
			exit(EXIT_FAILURE);
		}
	}

	/* Make the wordbreak table */
	make_wb_table();

	/* Finally, write it out */
	write_file(argv[1]);
	free(ucd_lo);
	free(ucd_mid);
	free(ucd_props);
	free(d_char);
	free(c_table);
	return 0;
}

