MAINTAINERCLEANFILES = Makefile.in

SUBDIRS = airport \
         animate \
         drag_and_drop \
         draw \
         earth \
         filemanager \
         fileview \
         font_dialog \
         getsubres \
         hellomotif \
         hellomotifi18n \
         i18ninput \
         panner \
         periodic \
         piano \
         popups \
         sampler2_0 \
         setdate \
         Exm \
         todo \
         workspace \
         tooltips \
         ButtonBox \
         Column \
         Outline \
         TabStack \
         Tree \
         ColorSel \
         Combo2 \
         Ext18List \
         IconB \
         Paned \
         pixmaps

